// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQUBms22f25S-CtiAq_ieHPiU2ekRBWPs',
    appId: '1:895724269212:web:0b818e791243570d6e8759',
    messagingSenderId: '895724269212',
    projectId: 'auth-9751d',
    authDomain: 'auth-9751d.firebaseapp.com',
    storageBucket: 'auth-9751d.firebasestorage.app',
    measurementId: 'G-4Z9GJZ2K01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1YzRgzFeCrAdnfCqnDooqe791ZD7g7Q',
    appId: '1:895724269212:android:6a6da6d18c4306fe6e8759',
    messagingSenderId: '895724269212',
    projectId: 'auth-9751d',
    storageBucket: 'auth-9751d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5anlAMa3TJAQeDQeD_zSo-vk7_-lFLJw',
    appId: '1:895724269212:ios:267513c0362694db6e8759',
    messagingSenderId: '895724269212',
    projectId: 'auth-9751d',
    storageBucket: 'auth-9751d.firebasestorage.app',
    iosClientId: '895724269212-fi8ks63afntl74jgul2dnn8dhqasp3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ltddAlovu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5anlAMa3TJAQeDQeD_zSo-vk7_-lFLJw',
    appId: '1:895724269212:ios:267513c0362694db6e8759',
    messagingSenderId: '895724269212',
    projectId: 'auth-9751d',
    storageBucket: 'auth-9751d.firebasestorage.app',
    iosClientId: '895724269212-fi8ks63afntl74jgul2dnn8dhqasp3rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ltddAlovu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQUBms22f25S-CtiAq_ieHPiU2ekRBWPs',
    appId: '1:895724269212:web:0ead4a4b792086526e8759',
    messagingSenderId: '895724269212',
    projectId: 'auth-9751d',
    authDomain: 'auth-9751d.firebaseapp.com',
    storageBucket: 'auth-9751d.firebasestorage.app',
    measurementId: 'G-ZHW3R2LBEH',
  );

}